theme: jekyll-theme-slate
title: Hi, I am Qianhui Liu
description: I am a second-year graduate student of Department of Information Management in Peking University, China. I am currently looking for potential Ph.D. positions, please feel free to contact me!
